package com.github.mat_kubiak.tqs.bus_connector; // Generated by Selenium IDE

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.not;
import static org.hamcrest.MatcherAssert.assertThat;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.WebElement;

class FunctionalIntegrationTest {
  private WebDriver driver;

  @BeforeEach
  void setUp() {
    driver = new FirefoxDriver();
  }

  @AfterEach
  void tearDown() {
    driver.quit();
  }

  private void selectRome() {
    WebElement dropdown = driver.findElement(By.id("destinationCitySelector"));
    dropdown.findElement(By.xpath("./option[. = 'Rome']")).click();
  }

  @Test
  void BookValidTicket() {
    driver.get("http://localhost:8080/");

    selectRome();

    driver.findElement(By.cssSelector("#destinationCitySelector > option:nth-child(2)")).click();
    driver.findElement(By.id("dateSelector")).sendKeys("2024-04-18");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) button")).click();
    driver.findElement(By.id("firstNameInput")).click();
    driver.findElement(By.id("firstNameInput")).sendKeys("Ana");
    driver.findElement(By.id("lastNameInput")).sendKeys("Pereira");
    driver.findElement(By.cssSelector("button")).click();
    assertThat(driver.findElement(By.id("ticket-id")).getText(), not(""));
  }

  @Test
  void bookTicketInPast() {
    driver.get("http://localhost:8080/");

    selectRome();

    driver.findElement(By.cssSelector("#destinationCitySelector > option:nth-child(2)")).click();
    driver.findElement(By.id("dateSelector")).sendKeys("2024-03-07");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("tr:nth-child(1) button")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Bus Selector"));
  }

}
